---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-maas-scaled
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-maas-scaled-type
    actions:
      - method: merge
        path: .
#  replacement: true
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .vip.maas_vip
      dest:
        path: .values.network.maas_ingress.addr
data:
  values:
    network:
      maas_ingress:
        addr: '172.30.14.115/32'
...
