---
# This file defines a boot action for MaaS to deploy the ingress-ip-rules script
# to nodes, register with systemd, and runs the script on all PXE booted nodes.
# On the genesis node, this is a manual step detailed in deployment documentation.
schema: 'drydock/BootAction/v1'
metadata:
  schema: 'metadata/Document/v1'
  name: ingress-ip-rules
  storagePolicy: 'cleartext'
  layeringDefinition:
    abstract: false
    layer: type
  labels:
    application: 'drydock'
  substitutions:
    # Substitutions for cluster ingress
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.ip_rule.gateway
      dest:
        path: .assets[0].data
        pattern: DH_SUB_GATEWAY_IP
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .assets[0].data
        pattern: DH_SUB_POD_CIDR
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.bgp.ipv4.ingress_vip
      dest:
        path: .assets[0].data
        pattern: DH_SUB_INGRESS_CIDR
    # Substitutions for MAAS ingress
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.ip_rule.gateway
      dest:
        path: .assets[1].data
        pattern: DH_SUB_GATEWAY_IP
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .kubernetes.pod_cidr
      dest:
        path: .assets[1].data
        pattern: DH_SUB_POD_CIDR
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .calico.bgp.ipv4.maas_vip
      dest:
        path: .assets[1].data
        pattern: DH_SUB_INGRESS_CIDR

    # Substitution of the configure-ip-rules script into this bootaction
    - src:
        schema: pegleg/Script/v1
        name: configure-ip-rules
        path: .
      dest:
        path: .assets[2].data
data:
  signaling: false
  assets:
    - path: /etc/systemd/system/configure-ingress-ip-rules.service
      type: unit
      permissions: '444'
      data: |-
        [Unit]
        Description=IP Rules Initialization Service
        After=network-online.target local-fs.target

        [Service]
        Type=simple
        ExecStart=/opt/configure-ip-rules.sh -g DH_SUB_GATEWAY_IP -c DH_SUB_POD_CIDR -s DH_SUB_INGRESS_CIDR

        [Install]
        WantedBy=multi-user.target
      data_pipeline:
        - utf8_decode
    - path: /etc/systemd/system/configure-maas-ip-rules.service
      type: unit
      permissions: '444'
      data: |-
        [Unit]
        Description=IP Rules Initialization Service
        After=network-online.target local-fs.target configure-ingress-ip-rules.service

        [Service]
        Type=simple
        ExecStart=/opt/configure-ip-rules.sh -g DH_SUB_GATEWAY_IP -c DH_SUB_POD_CIDR -s DH_SUB_INGRESS_CIDR

        [Install]
        WantedBy=multi-user.target
      data_pipeline:
        - utf8_decode

    - path: /opt/configure-ip-rules.sh
      type: file
      permissions: '700'
      data_pipeline:
        - utf8_decode
...
